### ISSUE TITLE
New relayer channel to monitor 

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#112]
Add to monitoring and renew channel Bostrom-Axelar 
Bostrom client:  07-tendermint-35
Bostrom channel:  channel-14
Axelar client:  07-tendermint-79
Axelar channel: channel-52

Update once in 12 hrs

Rly address to monitor balance: axelar1yevlp8pu8c5jq75kjyvryjjtylpa7m0r0jskum 

Also add rly address for crescent to monitor balance only: cre1fejerulsacktdyfmaxk4lnw7nwnmpm0deymdd9

**Comment by broVeider** [comment]
Balances and revision heights are added to monitor.
