### ISSUE TITLE
Cleanup monitoring for api nodes

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#15]
Nodes to check:
juno-tick-api
osmo-api2
stargaze_api

Install exporter for SMART satus, add to grafana boards smart data graph
Check alerts for every node above for: 
- Block counter
- Free space
- SMART status

**Comment by broVeider** [comment]
Monitoring settings for these nodes have been fixed.

**Comment by altbro** [comment]
All set as requested.
