### ISSUE TITLE
Publish relayers addresses

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#167]
Collect and add to git

**Comment by altbro** [comment]
rly1
bostrom1y7hgwdjfn2hk0m9nwclav63apv8g42rmc6puqu
osmo12e8crhzuh4ea0tmr5m8ytx6l3nqer4vxkq8h2c
cosmos1yevlp8pu8c5jq75kjyvryjjtylpa7m0rtux7h6
axelar1yevlp8pu8c5jq75kjyvryjjtylpa7m0r0jskum
cre1fejerulsacktdyfmaxk4lnw7nwnmpm0deymdd9

rly2
bostrom1fejerulsacktdyfmaxk4lnw7nwnmpm0d7lumx0
desmos1fejerulsacktdyfmaxk4lnw7nwnmpm0df59c0s
pussy1fejerulsacktdyfmaxk4lnw7nwnmpm0d5nzk9x
juno1fejerulsacktdyfmaxk4lnw7nwnmpm0dt7tnl5
evmos1lm7f8eqe77e9rkk6w3rqw7newqv8gsgtam04we
gravity1fejerulsacktdyfmaxk4lnw7nwnmpm0deu6saq

@bro-n-bro-99 where do you think we can publish em?

**Comment by bro-n-bro-99** [comment]
add as lending redirecting link
