### ISSUE TITLE
Setup evmos api node 

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#19]
@broVeider 
https://github.com/tharsis/evmos/releases/tag/v1.1.1
setup as usual api  + monitoring
pruning - default

peers 
https://docs.google.com/spreadsheets/d/1uQIznYv7SKs61yhFlZ5fU7Ksi-de3bq4WNd2YsyOiuo/edit#gid=0

**Comment by broVeider** [comment]
Node has been set up. 
Appropriate monitoring boards added.
