### ISSUE TITLE
Setup domain names for bro API nodes

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#21]
Setup a proxy machine with domain names to major API nodes

**Comment by altbro** [comment]
@broVeider  create namecheap acc

**Comment by broVeider** [comment]
@altbro , please, check the following URL's:
https://lcd.bostrom.bronbro.io
https://rpc.bostrom.bronbro.io
https://lcd.gravity-bridge-3.bronbro.io
https://rpc.gravity-bridge-3.bronbro.io
https://lcd.juno-1.bronbro.io
https://rpc.juno-1.bronbro.io
https://lcd.microtick-1.bronbro.io
https://rpc.microtick-1.bronbro.io
https://lcd.omniflixhub-1.bronbro.io
https://rpc.omniflixhub-1.bronbro.io
https://lcd.osmosis-1.bronbro.io
https://rpc.osmosis-1.bronbro.io
https://lcd.stargaze-1.bronbro.io
https://rpc.stargaze-1.bronbro.io
https://lcd.emoney-3.bronbro.io
https://rpc.emoney-3.bronbro.io
https://lcd.evmos-9001-2.bronbro.io
https://rpc.evmos-9001-2.bronbro.io

**Comment by altbro** [comment]
Well done
