### ISSUE TITLE
Create neutron arch api endpoints

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#248]
with our typicall arch api domain, but for neutron chain 
pass to krk6 accordingly for rpc, grpc and lcd

**Comment by broVeider** [comment]
https://rpc.neutron-1.arch.bronbro.io/
https://grpc.neutron-1.arch.bronbro.io:443/
https://grpc.neutron-1.arch.bronbro.io:1443/
https://lcd.neutron-1.arch.bronbro.io/
