### ISSUE TITLE
Testnets participation

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#259]
- [x] - Namada #250
- [x] - Avaial rollups - expired
- [x] - Babylon chain #266
- [ ] Artela #267
- [ ] Arkeo #268
- [x] Lava - #263 
- [ ] Ethos #269 
- [x] Penumbra #270
- [x] Initia #271
- [x] Seda #272

**Comment by bro-n-bro-2** [comment]
Babylon:
Discrod: https://discord.gg/babylonglobal
Faucet in Discord. Try to be in active set, let me know, if you need an assistance with it.

**Comment by bro-n-bro-2** [comment]
Artela:
Discord: https://discord.gg/QExVWGvr
Faucet in Discord.
Get a validator role and ask to assign the same role to cyberobionebro_n_brovalidator and mr_bro_n_bro

**Comment by bro-n-bro-2** [comment]
Arkeo:
Discord: https://discord.com/invite/BfEHpm6uFc
Guide: https://nodes.guru/testnets/arkeo/setup-guide/en
Faucet in Discord.
Get a validator role and ask to assign the same role to cyberobionebro_n_brovalidator and mr_bro_n_bro

**Comment by maximxmoroz** [comment]
Babylon node is up

**Comment by maximxmoroz** [comment]
Artela node is up

**Comment by maximxmoroz** [comment]
Arkeo node is up

**Comment by bro-n-bro-2** [comment]
Ethos: https://twitter.com/EthosStake

**Comment by bro-n-bro-2** [comment]
Penumbra: https://twitter.com/penumbrazone

**Comment by bro-n-bro-2** [comment]
Initia: https://twitter.com/initiaFDN

**Comment by bro-n-bro-2** [comment]
Shogun: https://twitter.com/shogunfi

**Comment by bro-n-bro-2** [comment]
Seda: https://twitter.com/sedaprotocol
