### ISSUE TITLE
Artela

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_infra#267]
Artela:
Discord: https://discord.gg/QExVWGvr
Github: https://github.com/artela-network/artela/
https://docs.artela.network/develop/node/run-full-node 
Faucet in Discord.

To get role - go to self-assign roles channel

**Comment by bro-n-bro-2** [comment]
please, do it after call @maximxmoroz

**Comment by maximxmoroz** [comment]
artela is up
