### ISSUE TITLE
Create account balance exporter.

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#28]
Create script for pulling specific account balance -> to file suitable for node_exporter.
Move current account trackers from python exporters to script setup. 
Accounts to track : restake bot. (Relayer accounta already tracked by hermes)

**Comment by broVeider** [comment]
@altbro. please, check the following board:
https://monitor.bronbro.io/d/xtIlAzrnk/restake-and-rly-balances?orgId=1
