### ISSUE TITLE
An additional server with empty postgres and hasura

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro_infra#3]
for bro statistic issues

**Comment by altbro** [comment]
@bro-n-bro-0 please specify hw requirements for such machine, as well as the purpose of it.

**Comment by bro-n-bro-0** [comment]
> @bro-n-bro-0 please specify hw requirements for such machine, as well as the purpose of it.

@altbro

it'll be used for static analytic tables and lottery services. 

I'm not expecting significant memory usage, so 250Gb suppose to be enough. But game monitors will be queried frequently

**Comment by altbro** [comment]
@broVeider pls proceed with new node setup, ip and details in keystore (postgres-hasura-node)
use [script](https://github.com/bro-n-bro/bro_infra/tree/main/scripts) for flow check on new node setup
launch docker containers with
- postgress 
- hasura 
using [this](https://github.com/cybercongress/cyberindex/blob/main/docker-compose.yml) docker compose
add access creds  to keystrore
