### ISSUE TITLE
Investigate juno API performance falling

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro_infra#36]
Cant grab data from the staking endpoint

https://lcd.juno-1.bronbro.io/staking/validators/junovaloper1quqxfrxkycr0uzt4yk0d57tcq3zk7srm7sm6r8/delegations?limit=1000000

**Comment by altbro** [comment]
Node is ready to be set. @broVeider plaese setup

**Comment by broVeider** [comment]
New node is ready. 
API backend changed to new server.
