### ISSUE TITLE
Akash research 

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_infra#363]
Akash research

**Comment by bro-n-bro-99** [comment]
the form is filled out

Akash Network Validator Program Application
https://akashnet.typeform.com/to/kH2gpXOL?typeform-source=github.com

**Comment by bro-n-bro-99** [comment]
if we don't hear from akash for a week, there is a way to follow up through the email 
delegations@akash.network

**Comment by bro-n-bro-99** [comment]
follow up email is sent
