### ISSUE TITLE
Setup Empeiria  testnet

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_infra#384]
Empeiria is the first foundational infrastructure for compliant non-fungible RWAs tokenization that seamlessly bridges on-chain and off-chain worlds, empowering builders to create innovative dApps with minimum effort. Powered by proprietary Empe L1 modular blockchain (Cosmos SDK, PoS).

Value proposition:
 
🌟Web2: Highest value-to-cost verifiable data infrastructure on the market with one-click deployment extending on Self-Sovereign Identity concept
         ⬇️
Bridging web2 to web3 for non-fungible RWA Tokenization
         ⬇️
🌟Web3: New classes of dApps with verifiable data in Smart Contracts and cross-chain interoperability

Our vision is to transform digital interactions with cryptographic truth and decentralized trust by unlocking new classes of dApps powered by verifiable data and enabling real-world adoption of web3 of the non-fungible RWAs tokenization.

🏆Highlights:
- 16,000h+ R&D and 130+ customer interactions to adjust product market fit
- Testnet released in April 2024 and decentralized with 200+ validators 
- Demo showcase with the reference verifiable data wallet
- Unique protocol economic model
- Regulatory advisor and pilot for the biggest world institution and central bank
- Telegram mini app for community engagement 

Validators docks: https://docs.empe.io/validators/overview
Validators group: https://t.me/EmpeValidators
Website: http://www.empe.io/
Showcase Demo: https://issuer-demo.empe.io/
Explorer: https://explorer-testnet.empe.io/
X:  https://twitter.com/empe_io
LinkedIn: https://www.linkedin.com/company/empe-web3

**Comment by broVeider** [comment]
https://explorer-testnet.empe.io/validators/empevaloper1zfm46r2jqg6n56urx2a6cesua94w68s76fx72g
