### ISSUE TITLE
Akash further setup

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_infra#385]
create validator key +
api node +
grafana board +
relayer Cosmos-AKT-OSMO
public API,RPC, - chain registry +
uptime +
restake +

**Comment by broVeider** [comment]
API and uptime ready

**Comment by broVeider** [comment]
https://github.com/cosmos/chain-registry/pull/5555

**Comment by broVeider** [comment]
https://github.com/eco-stake/validator-registry/pull/4607
