### ISSUE TITLE
Shutdown Microtick validator

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#39]
Post a tweet for delegators to restake to DIscoveryDEX validator

Undelegate all tokens from self-bro

**Comment by bro-n-bro-0** [comment]
shut down in the 20th July

**Comment by altbro** [comment]
@bro-n-bro-99 
Please post tweet-reminder that node will be shut tomorrow

**Comment by altbro** [comment]
Redelegated all sef-bont to discovery-DEX validator
