### ISSUE TITLE
Replace Microtick to Desmos nodes

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#42]
Re-set up mikrotick nodes to desmos. 
Api default pruning, for val - pruned.

**Comment by altbro** [comment]
Setup API dns for desmos @broVeider

**Comment by broVeider** [comment]
API/validator nodes have been prepared. 
Endpoints for API created: 
- https://rpc.desmos-mainnet.bronbro.io
- https://lcd.desmos-mainnet.bronbro.io
