### ISSUE TITLE
Move Omniflix API to new node

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro_infra#87]
- [x] Move Omniflix API to old osmosis RLY node 
- [x] Rename host, 
- [x] adjust alerts and naming in grafana
- [ ] delete old server

**Comment by broVeider** [comment]
Omniflix API moved.
Servers renamed: 
omniflix-api - old-omniflix-api
osmosis-rly - omniflix-api
Datasources changed in grafana

**Comment by altbro** [comment]
remove indexer and release the node
