### ISSUE TITLE
Migrate boards/bots to dedicated small server

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_infra#9]
Time to time we have issues, when boards don't work due to server maintenance. 
To avoid this, I suggest to move mentioned services to new server.

**Comment by altbro** [comment]
@bro-n-bro-2 Server is ready for migration

**Comment by altbro** [comment]
@bro-n-bro-2 Please close if done.

**Comment by altbro** [comment]
All migrated, tested.
